version: '3'
services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=odoo
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  odoo:
    image: odoo:17.0
    depends_on:
      - db
    ports:
      - "8090:8069"
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
    volumes:
      - type: bind
        source: /d/RUNNING APPS/ready production/latest/OSUSAPPS/payment_account_enhanced
        target: /mnt/extra-addons/payment_account_enhanced
      - type: bind
        source: /d/RUNNING APPS/ready production/latest/OSUSAPPS/commission_ax
        target: /mnt/extra-addons/commission_ax
      - type: bind
        source: /d/RUNNING APPS/ready production/latest/OSUSAPPS/commission_partner_statement
        target: /mnt/extra-addons/commission_partner_statement
      - type: bind
        source: /d/RUNNING APPS/ready production/latest/OSUSAPPS/odoo.conf
        target: /etc/odoo/odoo.conf
      - odoo-data:/var/lib/odoo

volumes:
  db-data:
  odoo-data: