version: '3.1'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: odoo
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  odoo:
    image: odoo:17.0
    depends_on:
      - db
    ports:
      - "8090:8069"
    environment:
      HOST: db
      USER: odoo
      PASSWORD: odoo
      # SSL Fix for wkhtmltopdf
      OPENSSL_CONF: /etc/ssl/
      SSL_CERT_FILE: /etc/ssl/certs/ca-certificates.crt
      SSL_CERT_DIR: /etc/ssl/certs
    volumes:
      - ./commission_ax:/mnt/extra-addons/commission_ax
      - ./commission_partner_statement:/mnt/extra-addons/commission_partner_statement
      - ./enhanced_status:/mnt/extra-addons/enhanced_status
      - ./odoo.conf:/etc/odoo/odoo.conf
      - odoo_data:/var/lib/odoo
    command: odoo -c /etc/odoo/odoo.conf
volumes:
  db_data:
  odoo_data:
